# This is the config file for SpawnStar plugin

# localized language support
language: en-US

# enabled worlds list
enabled-worlds:
  - world
  - world_nether
  - world_the_end

# material to be used as spawnstar item
itemmaterial: NETHER_STAR

# minimum distance from spawn
mindistance: 10

# require shift-click to use spawnstar item
shift-click: true

# allow spawnstar items to be used in crafting recipes
allow-crafting: false

# cooldown time in seconds
cooldown: 60

# warmup time in seconds
warmup: 5

# particle effects during warmup
particle-effects: true

# write log entry on use
log-use: true

# if player is in netherworld, try to respawn in matching overworld
from-nether: true

# if player is in end world, try to respawn in matching overworld
from-end: true

# lightning strike at spawn location on use
lightning: true
